// flow-typed signature: 42d4dbc8a066432254599c2d1c4bce92
// flow-typed version: <<STUB>>/react-native-web_v0.0.68/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-web/dist/apis/Animated/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/ReactNativeApp' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/renderApplication' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppState/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AsyncStorage/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/BackAndroid/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Clipboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Dimensions/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/I18nManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/InteractionManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Linking/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/NetInfo/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/PanResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/PixelRatio/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Platform/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/createReactDOMStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/expandStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/flattenStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/generateCss' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/hyphenate' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/i18nStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/initialize' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/injector' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/prefixInlineStyles' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/registry' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/resolveBoxShadow' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/resolveTextShadow' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/resolveTransform' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/StyleSheetValidation' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/UIManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Vibration/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ActivityIndicator/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Button/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/ListViewDataSource' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/ListViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ScrollView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ScrollView/ScrollViewBase' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StaticContainer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StaticRenderer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Switch/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/TextInputState' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/ensureComponentIsNative' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/core' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/applyLayout/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/applyNativeMethods/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/createDOMElement/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/dismissKeyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/findNodeHandle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/flattenArray/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ImageLoader/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/injectResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/mapKeyValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/multiplyStyleLengthValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/NativeMethodsMixin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/NativeModules/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/normalizeNativeEvent' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ReactNativePropRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ScrollResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/AnimationPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/BaseComponentPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/EdgeInsetsPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/PointPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/ShadowPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/TextPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/ReactNative' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/tests.webpack' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Animated/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppRegistry/ReactNativeApp' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppRegistry/renderApplication' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppState/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AsyncStorage/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/BackAndroid/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Clipboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Dimensions/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/I18nManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/InteractionManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Linking/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/NetInfo/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/PanResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/PixelRatio/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Platform/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/createReactDOMStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/expandStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/flattenStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/generateCss' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/hyphenate' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/i18nStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/initialize' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/injector' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/prefixInlineStyles' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/registry' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/resolveBoxShadow' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/resolveTextShadow' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/resolveTransform' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/StyleSheetValidation' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/UIManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Vibration/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ActivityIndicator/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Button/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ListView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ListView/ListViewDataSource' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ListView/ListViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ScrollView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ScrollView/ScrollViewBase' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/StaticContainer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/StaticRenderer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Switch/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Text/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/TextInput/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/TextInput/TextInputState' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/ensureComponentIsNative' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/View/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/core' {
  declare module.exports: any;
}

declare module 'react-native-web/src/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/applyLayout/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/applyNativeMethods/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/createDOMElement/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/dismissKeyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/findNodeHandle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/flattenArray/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/ImageLoader/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/injectResponderEventPlugin' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/mapKeyValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/multiplyStyleLengthValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/NativeMethodsMixin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/NativeModules/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/normalizeNativeEvent' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/ReactNativePropRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/ScrollResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/AnimationPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/BaseComponentPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/EdgeInsetsPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/PointPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/ShadowPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/TextPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/tests.webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-web/dist/apis/Animated/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Animated/index'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/index'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/ReactNativeApp.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/ReactNativeApp'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/renderApplication.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/renderApplication'>;
}
declare module 'react-native-web/dist/apis/AppState/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppState/index'>;
}
declare module 'react-native-web/dist/apis/AsyncStorage/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AsyncStorage/index'>;
}
declare module 'react-native-web/dist/apis/BackAndroid/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/BackAndroid/index'>;
}
declare module 'react-native-web/dist/apis/Clipboard/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Clipboard/index'>;
}
declare module 'react-native-web/dist/apis/Dimensions/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Dimensions/index'>;
}
declare module 'react-native-web/dist/apis/I18nManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/I18nManager/index'>;
}
declare module 'react-native-web/dist/apis/InteractionManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/InteractionManager/index'>;
}
declare module 'react-native-web/dist/apis/Linking/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Linking/index'>;
}
declare module 'react-native-web/dist/apis/NetInfo/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/NetInfo/index'>;
}
declare module 'react-native-web/dist/apis/PanResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/PanResponder/index'>;
}
declare module 'react-native-web/dist/apis/PixelRatio/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/PixelRatio/index'>;
}
declare module 'react-native-web/dist/apis/Platform/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Platform/index'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/createReactDOMStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/createReactDOMStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/expandStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/expandStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/flattenStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/flattenStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/generateCss.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/generateCss'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/hyphenate.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/hyphenate'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/i18nStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/i18nStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/index'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/initialize.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/initialize'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/injector.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/injector'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/normalizeValue'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/prefixInlineStyles.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/prefixInlineStyles'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/registry.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/registry'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/resolveBoxShadow.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/resolveBoxShadow'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/resolveTextShadow.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/resolveTextShadow'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/resolveTransform.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/resolveTransform'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/StyleSheetValidation.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/StyleSheetValidation'>;
}
declare module 'react-native-web/dist/apis/UIManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/UIManager/index'>;
}
declare module 'react-native-web/dist/apis/Vibration/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Vibration/index'>;
}
declare module 'react-native-web/dist/components/ActivityIndicator/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ActivityIndicator/index'>;
}
declare module 'react-native-web/dist/components/Button/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Button/index'>;
}
declare module 'react-native-web/dist/components/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageResizeMode'>;
}
declare module 'react-native-web/dist/components/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageStylePropTypes'>;
}
declare module 'react-native-web/dist/components/Image/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/index'>;
}
declare module 'react-native-web/dist/components/ListView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/index'>;
}
declare module 'react-native-web/dist/components/ListView/ListViewDataSource.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/ListViewDataSource'>;
}
declare module 'react-native-web/dist/components/ListView/ListViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/ListViewPropTypes'>;
}
declare module 'react-native-web/dist/components/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ProgressBar/index'>;
}
declare module 'react-native-web/dist/components/ScrollView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ScrollView/index'>;
}
declare module 'react-native-web/dist/components/ScrollView/ScrollViewBase.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ScrollView/ScrollViewBase'>;
}
declare module 'react-native-web/dist/components/StaticContainer/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StaticContainer/index'>;
}
declare module 'react-native-web/dist/components/StaticRenderer/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StaticRenderer/index'>;
}
declare module 'react-native-web/dist/components/Switch/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Switch/index'>;
}
declare module 'react-native-web/dist/components/Text/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/index'>;
}
declare module 'react-native-web/dist/components/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/TextStylePropTypes'>;
}
declare module 'react-native-web/dist/components/TextInput/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/index'>;
}
declare module 'react-native-web/dist/components/TextInput/TextInputState.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/TextInputState'>;
}
declare module 'react-native-web/dist/components/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/BoundingDimensions'>;
}
declare module 'react-native-web/dist/components/Touchable/ensureComponentIsNative.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/ensureComponentIsNative'>;
}
declare module 'react-native-web/dist/components/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-native-web/dist/components/Touchable/Position.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/Position'>;
}
declare module 'react-native-web/dist/components/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/Touchable'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableHighlight'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableOpacity'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableWithoutFeedback'>;
}
declare module 'react-native-web/dist/components/View/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/index'>;
}
declare module 'react-native-web/dist/components/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/ViewStylePropTypes'>;
}
declare module 'react-native-web/dist/core.js' {
  declare module.exports: $Exports<'react-native-web/dist/core'>;
}
declare module 'react-native-web/dist/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/index'>;
}
declare module 'react-native-web/dist/modules/applyLayout/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/applyLayout/index'>;
}
declare module 'react-native-web/dist/modules/applyNativeMethods/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/applyNativeMethods/index'>;
}
declare module 'react-native-web/dist/modules/createDOMElement/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/createDOMElement/index'>;
}
declare module 'react-native-web/dist/modules/dismissKeyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/dismissKeyboard/index'>;
}
declare module 'react-native-web/dist/modules/findNodeHandle/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/findNodeHandle/index'>;
}
declare module 'react-native-web/dist/modules/flattenArray/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/flattenArray/index'>;
}
declare module 'react-native-web/dist/modules/ImageLoader/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ImageLoader/index'>;
}
declare module 'react-native-web/dist/modules/injectResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/injectResponderEventPlugin'>;
}
declare module 'react-native-web/dist/modules/mapKeyValue/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/mapKeyValue/index'>;
}
declare module 'react-native-web/dist/modules/multiplyStyleLengthValue/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/multiplyStyleLengthValue/index'>;
}
declare module 'react-native-web/dist/modules/NativeMethodsMixin/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/NativeMethodsMixin/index'>;
}
declare module 'react-native-web/dist/modules/NativeModules/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/NativeModules/index'>;
}
declare module 'react-native-web/dist/modules/normalizeNativeEvent.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/normalizeNativeEvent'>;
}
declare module 'react-native-web/dist/modules/ReactNativePropRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ReactNativePropRegistry/index'>;
}
declare module 'react-native-web/dist/modules/ScrollResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ScrollResponder/index'>;
}
declare module 'react-native-web/dist/propTypes/AnimationPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/AnimationPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/BaseComponentPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/BaseComponentPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/BorderPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/ColorPropType'>;
}
declare module 'react-native-web/dist/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-native-web/dist/propTypes/EdgeInsetsPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/EdgeInsetsPropType'>;
}
declare module 'react-native-web/dist/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/LayoutPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/PointPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/PointPropType'>;
}
declare module 'react-native-web/dist/propTypes/ShadowPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/ShadowPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/StyleSheetPropType'>;
}
declare module 'react-native-web/dist/propTypes/TextPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/TextPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/TransformPropTypes'>;
}
declare module 'react-native-web/dist/ReactNative.js' {
  declare module.exports: $Exports<'react-native-web/dist/ReactNative'>;
}
declare module 'react-native-web/dist/tests.webpack.js' {
  declare module.exports: $Exports<'react-native-web/dist/tests.webpack'>;
}
declare module 'react-native-web/src/apis/Animated/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Animated/index'>;
}
declare module 'react-native-web/src/apis/AppRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppRegistry/index'>;
}
declare module 'react-native-web/src/apis/AppRegistry/ReactNativeApp.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppRegistry/ReactNativeApp'>;
}
declare module 'react-native-web/src/apis/AppRegistry/renderApplication.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppRegistry/renderApplication'>;
}
declare module 'react-native-web/src/apis/AppState/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppState/index'>;
}
declare module 'react-native-web/src/apis/AsyncStorage/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AsyncStorage/index'>;
}
declare module 'react-native-web/src/apis/BackAndroid/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/BackAndroid/index'>;
}
declare module 'react-native-web/src/apis/Clipboard/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Clipboard/index'>;
}
declare module 'react-native-web/src/apis/Dimensions/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Dimensions/index'>;
}
declare module 'react-native-web/src/apis/I18nManager/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/I18nManager/index'>;
}
declare module 'react-native-web/src/apis/InteractionManager/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/InteractionManager/index'>;
}
declare module 'react-native-web/src/apis/Linking/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Linking/index'>;
}
declare module 'react-native-web/src/apis/NetInfo/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/NetInfo/index'>;
}
declare module 'react-native-web/src/apis/PanResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/PanResponder/index'>;
}
declare module 'react-native-web/src/apis/PixelRatio/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/PixelRatio/index'>;
}
declare module 'react-native-web/src/apis/Platform/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Platform/index'>;
}
declare module 'react-native-web/src/apis/StyleSheet/createReactDOMStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/createReactDOMStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/expandStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/expandStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/flattenStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/flattenStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/generateCss.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/generateCss'>;
}
declare module 'react-native-web/src/apis/StyleSheet/hyphenate.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/hyphenate'>;
}
declare module 'react-native-web/src/apis/StyleSheet/i18nStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/i18nStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/index'>;
}
declare module 'react-native-web/src/apis/StyleSheet/initialize.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/initialize'>;
}
declare module 'react-native-web/src/apis/StyleSheet/injector.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/injector'>;
}
declare module 'react-native-web/src/apis/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/normalizeValue'>;
}
declare module 'react-native-web/src/apis/StyleSheet/prefixInlineStyles.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/prefixInlineStyles'>;
}
declare module 'react-native-web/src/apis/StyleSheet/registry.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/registry'>;
}
declare module 'react-native-web/src/apis/StyleSheet/resolveBoxShadow.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/resolveBoxShadow'>;
}
declare module 'react-native-web/src/apis/StyleSheet/resolveTextShadow.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/resolveTextShadow'>;
}
declare module 'react-native-web/src/apis/StyleSheet/resolveTransform.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/resolveTransform'>;
}
declare module 'react-native-web/src/apis/StyleSheet/StyleSheetValidation.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/StyleSheetValidation'>;
}
declare module 'react-native-web/src/apis/UIManager/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/UIManager/index'>;
}
declare module 'react-native-web/src/apis/Vibration/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Vibration/index'>;
}
declare module 'react-native-web/src/components/ActivityIndicator/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ActivityIndicator/index'>;
}
declare module 'react-native-web/src/components/Button/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Button/index'>;
}
declare module 'react-native-web/src/components/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/ImageResizeMode'>;
}
declare module 'react-native-web/src/components/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/ImageStylePropTypes'>;
}
declare module 'react-native-web/src/components/Image/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/index'>;
}
declare module 'react-native-web/src/components/ListView/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ListView/index'>;
}
declare module 'react-native-web/src/components/ListView/ListViewDataSource.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ListView/ListViewDataSource'>;
}
declare module 'react-native-web/src/components/ListView/ListViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ListView/ListViewPropTypes'>;
}
declare module 'react-native-web/src/components/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ProgressBar/index'>;
}
declare module 'react-native-web/src/components/ScrollView/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ScrollView/index'>;
}
declare module 'react-native-web/src/components/ScrollView/ScrollViewBase.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ScrollView/ScrollViewBase'>;
}
declare module 'react-native-web/src/components/StaticContainer/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/StaticContainer/index'>;
}
declare module 'react-native-web/src/components/StaticRenderer/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/StaticRenderer/index'>;
}
declare module 'react-native-web/src/components/Switch/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Switch/index'>;
}
declare module 'react-native-web/src/components/Text/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Text/index'>;
}
declare module 'react-native-web/src/components/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Text/TextStylePropTypes'>;
}
declare module 'react-native-web/src/components/TextInput/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/TextInput/index'>;
}
declare module 'react-native-web/src/components/TextInput/TextInputState.js' {
  declare module.exports: $Exports<'react-native-web/src/components/TextInput/TextInputState'>;
}
declare module 'react-native-web/src/components/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/BoundingDimensions'>;
}
declare module 'react-native-web/src/components/Touchable/ensureComponentIsNative.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/ensureComponentIsNative'>;
}
declare module 'react-native-web/src/components/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-native-web/src/components/Touchable/Position.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/Position'>;
}
declare module 'react-native-web/src/components/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/Touchable'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableHighlight'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableOpacity'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableWithoutFeedback'>;
}
declare module 'react-native-web/src/components/View/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/View/index'>;
}
declare module 'react-native-web/src/components/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/View/ViewStylePropTypes'>;
}
declare module 'react-native-web/src/core.js' {
  declare module.exports: $Exports<'react-native-web/src/core'>;
}
declare module 'react-native-web/src/index.js' {
  declare module.exports: $Exports<'react-native-web/src/index'>;
}
declare module 'react-native-web/src/modules/applyLayout/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/applyLayout/index'>;
}
declare module 'react-native-web/src/modules/applyNativeMethods/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/applyNativeMethods/index'>;
}
declare module 'react-native-web/src/modules/createDOMElement/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/createDOMElement/index'>;
}
declare module 'react-native-web/src/modules/dismissKeyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/dismissKeyboard/index'>;
}
declare module 'react-native-web/src/modules/findNodeHandle/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/findNodeHandle/index'>;
}
declare module 'react-native-web/src/modules/flattenArray/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/flattenArray/index'>;
}
declare module 'react-native-web/src/modules/ImageLoader/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/ImageLoader/index'>;
}
declare module 'react-native-web/src/modules/injectResponderEventPlugin.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/injectResponderEventPlugin'>;
}
declare module 'react-native-web/src/modules/mapKeyValue/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/mapKeyValue/index'>;
}
declare module 'react-native-web/src/modules/multiplyStyleLengthValue/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/multiplyStyleLengthValue/index'>;
}
declare module 'react-native-web/src/modules/NativeMethodsMixin/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/NativeMethodsMixin/index'>;
}
declare module 'react-native-web/src/modules/NativeModules/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/NativeModules/index'>;
}
declare module 'react-native-web/src/modules/normalizeNativeEvent.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/normalizeNativeEvent'>;
}
declare module 'react-native-web/src/modules/ReactNativePropRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/ReactNativePropRegistry/index'>;
}
declare module 'react-native-web/src/modules/ScrollResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/ScrollResponder/index'>;
}
declare module 'react-native-web/src/propTypes/AnimationPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/AnimationPropTypes'>;
}
declare module 'react-native-web/src/propTypes/BaseComponentPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/BaseComponentPropTypes'>;
}
declare module 'react-native-web/src/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/BorderPropTypes'>;
}
declare module 'react-native-web/src/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/ColorPropType'>;
}
declare module 'react-native-web/src/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-native-web/src/propTypes/EdgeInsetsPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/EdgeInsetsPropType'>;
}
declare module 'react-native-web/src/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/LayoutPropTypes'>;
}
declare module 'react-native-web/src/propTypes/PointPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/PointPropType'>;
}
declare module 'react-native-web/src/propTypes/ShadowPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/ShadowPropTypes'>;
}
declare module 'react-native-web/src/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/StyleSheetPropType'>;
}
declare module 'react-native-web/src/propTypes/TextPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/TextPropTypes'>;
}
declare module 'react-native-web/src/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/TransformPropTypes'>;
}
declare module 'react-native-web/src/tests.webpack.js' {
  declare module.exports: $Exports<'react-native-web/src/tests.webpack'>;
}
