// flow-typed signature: 837c5765fc0ee57ea17783be0d205dca
// flow-typed version: <<STUB>>/react-native-router-flux_v^3.37.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-flux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-flux/src/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Actions' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/DefaultRenderer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Switch' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/TabBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/TabbedView' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/Actions.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/Reducer.popAndReplace.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/Reducer.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-flux/index' {
  declare module.exports: $Exports<'react-native-router-flux'>;
}
declare module 'react-native-router-flux/index.js' {
  declare module.exports: $Exports<'react-native-router-flux'>;
}
declare module 'react-native-router-flux/src/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/ActionConst'>;
}
declare module 'react-native-router-flux/src/Actions.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Actions'>;
}
declare module 'react-native-router-flux/src/DefaultRenderer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/DefaultRenderer'>;
}
declare module 'react-native-router-flux/src/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Modal'>;
}
declare module 'react-native-router-flux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/NavBar'>;
}
declare module 'react-native-router-flux/src/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Reducer'>;
}
declare module 'react-native-router-flux/src/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Router'>;
}
declare module 'react-native-router-flux/src/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Scene'>;
}
declare module 'react-native-router-flux/src/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/State'>;
}
declare module 'react-native-router-flux/src/Switch.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Switch'>;
}
declare module 'react-native-router-flux/src/TabBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/TabBar'>;
}
declare module 'react-native-router-flux/src/TabbedView.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/TabbedView'>;
}
declare module 'react-native-router-flux/src/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Util'>;
}
declare module 'react-native-router-flux/test/Actions.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/Actions.test'>;
}
declare module 'react-native-router-flux/test/Reducer.popAndReplace.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/Reducer.popAndReplace.test'>;
}
declare module 'react-native-router-flux/test/Reducer.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/Reducer.test'>;
}
